// Pre-baked Natural Earth paths (Albers-projected) for North America.
// Generated by scripts/build-na-paths.js. D3 + topojson are dev-only.

import paths from "./data/north-america-paths.json";

export type NaFeature = {
  code: "CA" | "US" | "MX" | string;
  name: string;
  d: string;
};

export type NaPin = {
  name: string;
  x: number;
  y: number;
  hq?: boolean;
};

export const NA_WIDTH: number = paths.width;
export const NA_HEIGHT: number = paths.height;
export const NA_FEATURES: NaFeature[] = paths.features as NaFeature[];
export const NA_PINS: NaPin[] = paths.pins as NaPin[];
