// Auto-generated by local-authority-silo-engine.
// DO NOT EDIT BY HAND. Regenerate via:
//   python3 generate.py --brand <brand-name>
import bundle from "./content.json";

export type SiloPage = {
  type: "city_hub" | "service_in_city" | "blog";
  url: string;
  title: string;
  meta_description: string;
  city: string;
  city_key: string;
  state_abbr: string;
  state: string;
  country?: string;
  lat?: number;
  lng?: number;
  intro?: string;
  local_context?: string;
  service_details?: string;
  body?: string;
  service_slug?: string;
  service_label?: string;
  service_blurb?: string;
  authority_citations?: Array<{ name: string; url: string; context?: string }>;
  authority_citation?: { name: string; url: string; context?: string };
  faq?: Array<{ q: string; a: string }>;
  key_takeaways?: string[];
  image: string;
  image_alt: string;
  neighborhoods?: string[];
  jurisdiction?: { body: string; statute: string; url: string };
  city_hub_url?: string;
  service_in_city_url?: string;
  national_service_url?: string;
  topic?: string;
};

export type SiloBundle = {
  brand: string;
  domain: string;
  url: string;
  core_keyword: string;
  generated_at: string;
  pages: SiloPage[];
  redirects: Array<{ source: string; destination: string; permanent: boolean }>;
  stats: Record<string, number>;
};

export const SILO: SiloBundle = bundle as unknown as SiloBundle;

export const SILO_PAGES: SiloPage[] = SILO.pages;

export const CITY_HUBS = SILO_PAGES.filter((p) => p.type === "city_hub");
export const SERVICE_IN_CITY = SILO_PAGES.filter((p) => p.type === "service_in_city");
export const SILO_BLOGS = SILO_PAGES.filter((p) => p.type === "blog");

export function getCityHub(slug: string): SiloPage | undefined {
  return CITY_HUBS.find((p) => p.url === `/${slug}` || p.url === slug);
}

export function getSiloPage(url: string): SiloPage | undefined {
  const norm = url.startsWith("/") ? url : `/${url}`;
  return SILO_PAGES.find((p) => p.url === norm);
}

export function siloPagesByCity(cityKey: string): SiloPage[] {
  return SILO_PAGES.filter((p) => p.city_key === cityKey);
}
