// AUTO-GENERATED by local-authority-silo-engine.
import type { ReactNode } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Phone, ExternalLink } from "lucide-react";
import CTASection from "@/components/CTASection";
import PageHero from "@/components/PageHero";
import SectionHeading from "@/components/SectionHeading";
import SchemaJsonLd from "@/components/SchemaJsonLd";
import { breadcrumbSchema } from "@/lib/schema";
import { BRAND, NAP } from "@/lib/constants";
import { IMAGES } from "@/lib/images";
import bundle from "@/lib/silo/content.json";

type Params = { params: { slug: string } };

type SiloPage = {
  type: string;
  url: string;
  title: string;
  topic?: string;
  meta_description: string;
  city: string;
  state_abbr: string;
  service_label?: string;
  intro?: string;
  body?: string;
  key_takeaways?: string[];
  authority_citation?: { name: string; url: string; context?: string };
  image: string;
  image_alt: string;
  city_hub_url?: string;
  service_in_city_url?: string;
};

// Many bundle titles were truncated at 60 chars by the upstream generator
// (e.g. "...response in Ontario after hou"). The full text lives in `topic`.
// Prefer the longer of the two when a clean title is needed.
function displayTitle(page: SiloPage): string {
  const t = (page.title || "").trim();
  const topic = (page.topic || "").trim();
  if (topic && topic.length > t.length) return topic;
  return t || topic;
}

const ALL_PAGES = bundle.pages as SiloPage[];
const BLOGS = ALL_PAGES.filter((p) => p.type === "blog");

export const dynamic = "force-static";
export const dynamicParams = false;

export async function generateStaticParams() {
  return BLOGS.map((p) => ({ slug: p.url.replace("/blog/", "") }));
}

export function generateMetadata({ params }: Params) {
  const page = BLOGS.find((p) => p.url === `/blog/${params.slug}`);
  if (!page) return {};
  return {
    title: `${displayTitle(page)} | ${BRAND.name}`,
    description: page.meta_description,
    alternates: { canonical: `${BRAND.url}${page.url}` },
  };
}

function buildSchema(page: SiloPage) {
  const headline = displayTitle(page);
  return {
    "@context": "https://schema.org",
    "@graph": [
      breadcrumbSchema([
        { name: "Home", url: BRAND.url },
        { name: "Blog", url: `${BRAND.url}/blog` },
        { name: headline, url: `${BRAND.url}${page.url}` },
      ]),
      {
        "@type": "Article",
        headline,
        description: page.meta_description,
        author: { "@type": "Organization", name: BRAND.name },
        publisher: { "@type": "Organization", name: BRAND.name, url: BRAND.url },
        url: `${BRAND.url}${page.url}`,
      },
    ],
  };
}

// Bundle bodies are stored as a single line with literal "## " inline
// markdown headings and NO separator between heading text and body text.
// Older code split on \n\n which produced one giant block. We split on
// "## " then split each section so the first sentence becomes the heading
// and the rest becomes paragraph prose.
function renderBody(md: string) {
  if (!md) return null;
  const normalized = md.replace(/\r\n/g, "\n").trim();
  // Split into sections, each starting after a "## " marker.
  // The first part (before any ##) is treated as a lead paragraph.
  const parts = normalized.split(/\s*##\s+/);
  const nodes: ReactNode[] = [];
  parts.forEach((part, i) => {
    const text = part.trim();
    if (!text) return;
    if (i === 0) {
      // No leading "## " — render as plain paragraph(s).
      text.split(/\n{2,}/).forEach((p, j) => {
        if (p.trim()) {
          nodes.push(
            <p
              key={`p0-${j}`}
              className="text-steel-600 leading-relaxed mb-4"
            >
              {p.trim()}
            </p>
          );
        }
      });
      return;
    }
    // First sentence (or first line) is the heading; remainder is body.
    const headingMatch = text.match(/^([^.\n]+)([.\n]\s*)?/);
    const heading = headingMatch ? headingMatch[1].trim() : text;
    const remainder = headingMatch
      ? text.slice(headingMatch[0].length).trim()
      : "";
    nodes.push(
      <h2
        key={`h-${i}`}
        className="font-display text-2xl font-bold text-navy mt-8 mb-3"
      >
        {heading}
      </h2>
    );
    if (remainder) {
      remainder.split(/\n{2,}/).forEach((p, j) => {
        if (p.trim()) {
          nodes.push(
            <p
              key={`p-${i}-${j}`}
              className="text-steel-600 leading-relaxed mb-4"
            >
              {p.trim()}
            </p>
          );
        }
      });
    }
  });
  return nodes;
}

export default function SiloBlogPost({ params }: Params) {
  const page = BLOGS.find((p) => p.url === `/blog/${params.slug}`);
  if (!page) notFound();

  return (
    <>
      <SchemaJsonLd id={`ld-blog-${params.slug}`} data={buildSchema(page)} />

      <PageHero
        eyebrow="Local Guide"
        title={displayTitle(page)}
        description={page.meta_description}
        crumbs={[
          { name: "Home", href: "/" },
          { name: "Blog", href: "/blog" },
          { name: displayTitle(page) },
        ]}
        image={IMAGES.edLocationsHero}
        imageAlt={page.image_alt}
        variant="editorial"
      >
        <div className="flex flex-col gap-3 sm:flex-row">
          <a href={NAP.phoneTel} className="btn-accent">
            <Phone className="h-4 w-4" />
            {NAP.phone}
          </a>
        </div>
      </PageHero>

      <article className="bg-white section">
        <div className="container-bp prose prose-lg max-w-3xl">
          {page.intro && <p className="lead">{page.intro}</p>}
          {renderBody(page.body || "")}

          {page.key_takeaways && page.key_takeaways.length > 0 && (
            <>
              <h2 className="font-display text-2xl font-bold text-navy mt-10 mb-4">
                Key takeaways
              </h2>
              <ul className="list-disc pl-6 space-y-2">
                {page.key_takeaways.map((t, i) => (
                  <li key={i} className="text-steel-600">
                    {t}
                  </li>
                ))}
              </ul>
            </>
          )}

          {page.authority_citation && page.authority_citation.url && (
            <div className="mt-8 p-5 rounded-xl border border-steel-100 bg-cream-100">
              <p className="eyebrow mb-2">Authority source</p>
              <a
                href={page.authority_citation.url}
                target="_blank"
                rel="noopener noreferrer"
                className="font-semibold text-navy underline"
              >
                <ExternalLink className="h-4 w-4 inline mr-1" />
                {page.authority_citation.name}
              </a>
              {page.authority_citation.context && (
                <p className="text-sm text-steel-500 mt-1">
                  {page.authority_citation.context}
                </p>
              )}
            </div>
          )}
        </div>
      </article>

      <section className="bg-steel-50 section">
        <div className="container-bp grid grid-cols-1 md:grid-cols-2 gap-6 max-w-3xl">
          {page.city_hub_url && (
            <Link
              href={page.city_hub_url}
              className="rounded-xl border border-steel-100 bg-white p-5 hover:border-cyan-500 transition"
            >
              <p className="eyebrow mb-2">City hub</p>
              <p className="font-semibold text-navy">
                {page.city}, {page.state_abbr}
              </p>
            </Link>
          )}
          {page.service_in_city_url && (
            <Link
              href={page.service_in_city_url}
              className="rounded-xl border border-steel-100 bg-white p-5 hover:border-cyan-500 transition"
            >
              <p className="eyebrow mb-2">Service in this city</p>
              <p className="font-semibold text-navy">{page.service_label}</p>
            </Link>
          )}
        </div>
      </section>

      <CTASection />
    </>
  );
}
